name: check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  unix-test:
    runs-on: macos-latest
    env:
      WECOM_ROBOT_KEY: ${{ secrets.WECOM_ROBOT_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s bleeding
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: update mooncakes registry
        run: moon update

      - name: simple use
        run: |
          for i in *.sh; do
            bash $i
          done

      - name: notify on fail
        if: ${{ failure() }}
        run: |
          curl "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=$WECOM_ROBOT_KEY" \
            -H 'Content-Type: application/json' \
            -d @- <<REQUEST_BODY
            {
              "msgtype": "text",
              "text": {
                "content": "🤣 bleeding daily ci failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }
          REQUEST_BODY
